import { Product } from "./types/product";

export const PRODUCTS: Product[] = [
    {
        id: 1,
        name: "Healer",
        image: "visible/healer",
        rarity: 1,
        categoryId: 1,
        owner: 0,
        
        title: "Healer",
        slug: "healer",
        heroImage: require("../assets/characters/city-of-mercy/healer.png"),
        imagesUrl: [require("../assets/characters/city-of-mercy/healer.png")],
        price: 899.99,
        category: {
            imageUrl: require("../assets/characters/box_img.webp"),
            name: "City of Mercy",
            slug: "city of mercy",
        },
        maxQuantity: 5,
    },
    {
        id: 2,
        name: "idk",
        image: "visible/healer",
        rarity: 1,
        categoryId: 1,
        owner: 0,
        
        title: "Idk",
        slug: "healer",
        heroImage: require("../assets/characters/city-of-mercy/healer.png"),
        imagesUrl: [require("../assets/characters/city-of-mercy/healer.png")],
        price: 899.99,
        category: {
            imageUrl: require("../assets/characters/box_img.webp"),
            name: "Little Mischief",
            slug: "little mischief",
        },
        maxQuantity: 5,
    },
    // {
    //     id: 1,
    //     title: "The fox",
    //     slug: "the fox",
    //     heroImage: require("../assets/characters/the-other-one/the-fox.png"),
    //     imagesUrl: [require("../assets/characters/the-other-one/the-fox.png")],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "The Other One",
    //         slug: "the other one",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 2,
    //     title: "The monster",
    //     slug: "the monster",
    //     heroImage: require("../assets/characters/the-other-one/the-monster.png"),
    //     imagesUrl: [
    //         require("../assets/characters/the-other-one/the-monster.png"),
    //     ],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "The Other One",
    //         slug: "the other one",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 3,
    //     title: "Amnesia",
    //     slug: "amnesia",
    //     heroImage: require("../assets/characters/the-other-one/amnesia.png"),
    //     imagesUrl: [require("../assets/characters/the-other-one/amnesia.png")],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "The Other One",
    //         slug: "the other one",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 4,
    //     title: "Cuckoo",
    //     slug: "cuckoo",
    //     heroImage: require("../assets/characters/the-other-one/cuckoo.png"),
    //     imagesUrl: [require("../assets/characters/the-other-one/cuckoo.png")],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "The Other One",
    //         slug: "the other one",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 5,
    //     title: "Staring",
    //     slug: "staring",
    //     heroImage: require("../assets/characters/the-other-one/staring.png"),
    //     imagesUrl: [require("../assets/characters/the-other-one/staring.png")],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "The Other One",
    //         slug: "the other one",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 6,
    //     title: "Nowhere Safe",
    //     slug: "nowhere safe",
    //     heroImage: require("../assets/characters/the-other-one/nowhere-safe.png"),
    //     imagesUrl: [
    //         require("../assets/characters/the-other-one/nowhere-safe.png"),
    //     ],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "The Other One",
    //         slug: "the other one",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 7,
    //     title: "Raving",
    //     slug: "raving",
    //     heroImage: require("../assets/characters/the-other-one/raving.png"),
    //     imagesUrl: [require("../assets/characters/the-other-one/raving.png")],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "The Other One",
    //         slug: "the other one",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 8,
    //     title: "Marionette",
    //     slug: "marrionette",
    //     heroImage: require("../assets/characters/the-other-one/marrionette.png"),
    //     imagesUrl: [
    //         require("../assets/characters/the-other-one/marrionette.png"),
    //     ],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "The Other One",
    //         slug: "the other one",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 9,
    //     title: "Vagrancy",
    //     slug: "vagrancy",
    //     heroImage: require("../assets/characters/the-other-one/vagrancy.png"),
    //     imagesUrl: [require("../assets/characters/the-other-one/vagrancy.png")],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "The Other One",
    //         slug: "the other one",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 10,
    //     title: "Being Alive",
    //     slug: "being alive",
    //     heroImage: require("../assets/characters/the-other-one/being-alive.png"),
    //     imagesUrl: [
    //         require("../assets/characters/the-other-one/being-alive.png"),
    //     ],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "The Other One",
    //         slug: "the other one",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 11,
    //     title: "The Ghost",
    //     slug: "the ghost",
    //     heroImage: require("../assets/characters/the-other-one/the-ghost.png"),
    //     imagesUrl: [
    //         require("../assets/characters/the-other-one/the-ghost.png"),
    //     ],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "The Other One",
    //         slug: "the other one",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 12,
    //     title: "The Crow",
    //     slug: "the crow",
    //     heroImage: require("../assets/characters/the-other-one/the-crow.png"),
    //     imagesUrl: [require("../assets/characters/the-other-one/the-crow.png")],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "The Other One",
    //         slug: "the other one",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 13,
    //     title: "Dreaming",
    //     slug: "dreaming",
    //     heroImage: require("../assets/characters/the-other-one/dreaming.png"),
    //     imagesUrl: [require("../assets/characters/the-other-one/dreaming.png")],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "The Other One",
    //         slug: "the other one",
    //     },
    //     maxQuantity: 5,
    // },

    // {
    //     id: 14,
    //     title: "Birdman",
    //     slug: "birdman",
    //     heroImage: require("../assets/characters/little-mischief/birdman.png"),
    //     imagesUrl: [
    //         require("../assets/characters/little-mischief/birdman.png"),
    //     ],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Little Mischief",
    //         slug: "little mischief",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 15,
    //     title: "Boiling Frog",
    //     slug: "boiling frog",
    //     heroImage: require("../assets/characters/little-mischief/boiling-frog.png"),
    //     imagesUrl: [
    //         require("../assets/characters/little-mischief/boiling-frog.png"),
    //     ],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Little Mischief",
    //         slug: "little mischief",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 16,
    //     title: "Destroyer",
    //     slug: "destroyer",
    //     heroImage: require("../assets/characters/little-mischief/destroyer.png"),
    //     imagesUrl: [
    //         require("../assets/characters/little-mischief/destroyer.png"),
    //     ],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Little Mischief",
    //         slug: "little mischief",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 17,
    //     title: "Float",
    //     slug: "float",
    //     heroImage: require("../assets/characters/little-mischief/float.png"),
    //     imagesUrl: [require("../assets/characters/little-mischief/float.png")],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Little Mischief",
    //         slug: "little mischief",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 18,
    //     title: "Loose Fish",
    //     slug: "loose fish",
    //     heroImage: require("../assets/characters/little-mischief/loose-fish.png"),
    //     imagesUrl: [
    //         require("../assets/characters/little-mischief/loose-fish.png"),
    //     ],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Little Mischief",
    //         slug: "little mischief",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 19,
    //     title: "Manacle",
    //     slug: "manacle",
    //     heroImage: require("../assets/characters/little-mischief/manacle.png"),
    //     imagesUrl: [
    //         require("../assets/characters/little-mischief/manacle.png"),
    //     ],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Little Mischief",
    //         slug: "little mischief",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 20,
    //     title: "Persona",
    //     slug: "persona",
    //     heroImage: require("../assets/characters/little-mischief/persona.png"),
    //     imagesUrl: [
    //         require("../assets/characters/little-mischief/persona.png"),
    //     ],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Little Mischief",
    //         slug: "little mischief",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 21,
    //     title: "Pretender",
    //     slug: "pretender",
    //     heroImage: require("../assets/characters/little-mischief/pretender.png"),
    //     imagesUrl: [
    //         require("../assets/characters/little-mischief/pretender.png"),
    //     ],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Little Mischief",
    //         slug: "little mischief",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 22,
    //     title: "Protector",
    //     slug: "protector",
    //     heroImage: require("../assets/characters/little-mischief/protector.png"),
    //     imagesUrl: [
    //         require("../assets/characters/little-mischief/protector.png"),
    //     ],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Little Mischief",
    //         slug: "little mischief",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 23,
    //     title: "Ragpicker",
    //     slug: "ragpicker",
    //     heroImage: require("../assets/characters/little-mischief/ragpicker.png"),
    //     imagesUrl: [
    //         require("../assets/characters/little-mischief/ragpicker.png"),
    //     ],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Little Mischief",
    //         slug: "little mischief",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 24,
    //     title: "Robot",
    //     slug: "robot",
    //     heroImage: require("../assets/characters/little-mischief/robot.png"),
    //     imagesUrl: [require("../assets/characters/little-mischief/robot.png")],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Little Mischief",
    //         slug: "little mischief",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 25,
    //     title: "The Aviator",
    //     slug: "the aviator",
    //     heroImage: require("../assets/characters/little-mischief/the-aviator.png"),
    //     imagesUrl: [
    //         require("../assets/characters/little-mischief/the-aviator.png"),
    //     ],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Little Mischief",
    //         slug: "little mischief",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 26,
    //     title: "Unknown Journey",
    //     slug: "unknown journey",
    //     heroImage: require("../assets/characters/little-mischief/unknown-journey.png"),
    //     imagesUrl: [
    //         require("../assets/characters/little-mischief/unknown-journey.png"),
    //     ],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Little Mischief",
    //         slug: "little mischief",
    //     },
    //     maxQuantity: 5,
    // },

    // {
    //     id: 27,
    //     title: "Belonging",
    //     slug: "belonging",
    //     heroImage: require("../assets/characters/city-of-mercy/belonging.png"),
    //     imagesUrl: [
    //         require("../assets/characters/city-of-mercy/belonging.png"),
    //     ],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "City of Mercy",
    //         slug: "city of mercy",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 28,
    //     title: "Comfortably Numb",
    //     slug: "comfortably numb",
    //     heroImage: require("../assets/characters/city-of-mercy/comfortably-numb.png"),
    //     imagesUrl: [
    //         require("../assets/characters/city-of-mercy/comfortably-numb.png"),
    //     ],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "City of Mercy",
    //         slug: "city of mercy",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 29,
    //     title: "Echo",
    //     slug: "echo",
    //     heroImage: require("../assets/characters/city-of-mercy/echo.png"),
    //     imagesUrl: [require("../assets/characters/city-of-mercy/echo.png")],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "City of Mercy",
    //         slug: "city of mercy",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 30,
    //     title: "Fallen Angel",
    //     slug: "fallen angel",
    //     heroImage: require("../assets/characters/city-of-mercy/fallen-angel.png"),
    //     imagesUrl: [
    //         require("../assets/characters/city-of-mercy/fallen-angel.png"),
    //     ],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "City of Mercy",
    //         slug: "city of mercy",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 31,
    //     title: "Healer",
    //     slug: "healer",
    //     heroImage: require("../assets/characters/city-of-mercy/healer.png"),
    //     imagesUrl: [require("../assets/characters/city-of-mercy/healer.png")],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "City of Mercy",
    //         slug: "city of mercy",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 32,
    //     title: "Insight",
    //     slug: "insight",
    //     heroImage: require("../assets/characters/city-of-mercy/insight.png"),
    //     imagesUrl: [require("../assets/characters/city-of-mercy/insight.png")],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "City of Mercy",
    //         slug: "city of mercy",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 33,
    //     title: "The Other",
    //     slug: "the other",
    //     heroImage: require("../assets/characters/city-of-mercy/the-other.png"),
    //     imagesUrl: [
    //         require("../assets/characters/city-of-mercy/the-other.png"),
    //     ],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "City of Mercy",
    //         slug: "city of mercy",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 34,
    //     title: "Wandering",
    //     slug: "wandering",
    //     heroImage: require("../assets/characters/city-of-mercy/wandering.png"),
    //     imagesUrl: [
    //         require("../assets/characters/city-of-mercy/wandering.png"),
    //     ],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "City of Mercy",
    //         slug: "city of mercy",
    //     },
    //     maxQuantity: 5,
    // },

    // {
    //     id: 35,
    //     title: "Blind",
    //     slug: "blind",
    //     heroImage: require("../assets/characters/mime/blind.png"),
    //     imagesUrl: [require("../assets/characters/mime/blind.png")],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "MIME",
    //         slug: "mime",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 36,
    //     title: "Destroy",
    //     slug: "destroy",
    //     heroImage: require("../assets/characters/mime/destroy.png"),
    //     imagesUrl: [require("../assets/characters/mime/destroy.png")],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "MIME",
    //         slug: "mime",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 37,
    //     title: "Devilry",
    //     slug: "devilry",
    //     heroImage: require("../assets/characters/mime/devilry.png"),
    //     imagesUrl: [require("../assets/characters/mime/devilry.png")],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "MIME",
    //         slug: "mime",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 38,
    //     title: "Driften",
    //     slug: "driften",
    //     heroImage: require("../assets/characters/mime/driften.png"),
    //     imagesUrl: [require("../assets/characters/mime/driften.png")],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "MIME",
    //         slug: "mime",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 39,
    //     title: "Fool",
    //     slug: "fool",
    //     heroImage: require("../assets/characters/mime/fool.png"),
    //     imagesUrl: [require("../assets/characters/mime/fool.png")],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "MIME",
    //         slug: "mime",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 40,
    //     title: "Guardian",
    //     slug: "guardian",
    //     heroImage: require("../assets/characters/mime/guardian.png"),
    //     imagesUrl: [require("../assets/characters/mime/guardian.png")],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "MIME",
    //         slug: "mime",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 41,
    //     title: "Patience",
    //     slug: "patience",
    //     heroImage: require("../assets/characters/mime/patience.png"),
    //     imagesUrl: [require("../assets/characters/mime/patience.png")],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "MIME",
    //         slug: "mime",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 42,
    //     title: "Poem",
    //     slug: "poem",
    //     heroImage: require("../assets/characters/mime/poem.png"),
    //     imagesUrl: [require("../assets/characters/mime/poem.png")],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "MIME",
    //         slug: "mime",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 43,
    //     title: "Prison",
    //     slug: "prison",
    //     heroImage: require("../assets/characters/mime/prison.png"),
    //     imagesUrl: [require("../assets/characters/mime/prison.png")],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "MIME",
    //         slug: "mime",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 44,
    //     title: "Secrecy",
    //     slug: "secrecy",
    //     heroImage: require("../assets/characters/mime/secrecy.png"),
    //     imagesUrl: [require("../assets/characters/mime/secrecy.png")],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "MIME",
    //         slug: "mime",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 45,
    //     title: "Seeker",
    //     slug: "seeker",
    //     heroImage: require("../assets/characters/mime/seeker.png"),
    //     imagesUrl: [require("../assets/characters/mime/seeker.png")],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "MIME",
    //         slug: "mime",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 46,
    //     title: "Silence",
    //     slug: "silence",
    //     heroImage: require("../assets/characters/mime/silence.png"),
    //     imagesUrl: [require("../assets/characters/mime/silence.png")],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "MIME",
    //         slug: "mime",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 47,
    //     title: "Unspoken",
    //     slug: "unspoken",
    //     heroImage: require("../assets/characters/mime/unspoken.png"),
    //     imagesUrl: [require("../assets/characters/mime/unspoken.png")],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "MIME",
    //         slug: "mime",
    //     },
    //     maxQuantity: 5,
    // },

    // {
    //     id: 48,
    //     title: "Burst",
    //     slug: "burst",
    //     heroImage: require("../assets/characters/reshape/burst.png"),
    //     imagesUrl: [require("../assets/characters/reshape/burst.png")],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Reshape",
    //         slug: "reshape",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 49,
    //     title: "Costume",
    //     slug: "costume",
    //     heroImage: require("../assets/characters/reshape/costume.png"),
    //     imagesUrl: [require("../assets/characters/reshape/costume.png")],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Reshape",
    //         slug: "reshape",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 50,
    //     title: "Drowning",
    //     slug: "drowning",
    //     heroImage: require("../assets/characters/reshape/drowning.png"),
    //     imagesUrl: [require("../assets/characters/reshape/drowning.png")],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Reshape",
    //         slug: "reshape",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 51,
    //     title: "Fading",
    //     slug: "fading",
    //     heroImage: require("../assets/characters/reshape/fading.png"),
    //     imagesUrl: [require("../assets/characters/reshape/fading.png")],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Reshape",
    //         slug: "reshape",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 52,
    //     title: "Healing",
    //     slug: "healing",
    //     heroImage: require("../assets/characters/reshape/healing.png"),
    //     imagesUrl: [require("../assets/characters/reshape/healing.png")],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Reshape",
    //         slug: "reshape",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 53,
    //     title: "Paradise Lost",
    //     slug: "paradise lost",
    //     heroImage: require("../assets/characters/reshape/paradise-lost.png"),
    //     imagesUrl: [require("../assets/characters/reshape/paradise-lost.png")],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Reshape",
    //         slug: "reshape",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 54,
    //     title: "Parasite",
    //     slug: "parasite",
    //     heroImage: require("../assets/characters/reshape/parasite.png"),
    //     imagesUrl: [require("../assets/characters/reshape/parasite.png")],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Reshape",
    //         slug: "reshape",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 55,
    //     title: "Voyage",
    //     slug: "voyage",
    //     heroImage: require("../assets/characters/reshape/voyage.png"),
    //     imagesUrl: [require("../assets/characters/reshape/voyage.png")],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Reshape",
    //         slug: "reshape",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 56,
    //     title: "Woodcarving",
    //     slug: "woodcarving",
    //     heroImage: require("../assets/characters/reshape/woodcarving.png"),
    //     imagesUrl: [require("../assets/characters/reshape/woodcarving.png")],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Reshape",
    //         slug: "reshape",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 57,
    //     title: "Puppet",
    //     slug: "puppet",
    //     heroImage: require("../assets/characters/reshape/puppet.png"),
    //     imagesUrl: [require("../assets/characters/reshape/puppet.png")],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Reshape",
    //         slug: "reshape",
    //     },
    //     maxQuantity: 5,
    // },

    // {
    //     id: 58,
    //     title: "Alien",
    //     slug: "alien",
    //     heroImage: require("../assets/characters/shelter/alien.png"),
    //     imagesUrl: [require("../assets/characters/shelter/alien.png")],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Shelter",
    //         slug: "shelter",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 59,
    //     title: "Bird Cage",
    //     slug: "bird-cage",
    //     heroImage: require("../assets/characters/shelter/bird-cage.png"),
    //     imagesUrl: [require("../assets/characters/shelter/bird-cage.png")],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Shelter",
    //         slug: "shelter",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 60,
    //     title: "Birdy",
    //     slug: "birdy",
    //     heroImage: require("../assets/characters/shelter/birdy.png"),
    //     imagesUrl: [require("../assets/characters/shelter/birdy.png")],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Shelter",
    //         slug: "shelter",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 61,
    //     title: "Cabin",
    //     slug: "cabin",
    //     heroImage: require("../assets/characters/shelter/cabin.png"),
    //     imagesUrl: [require("../assets/characters/shelter/cabin.png")],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Shelter",
    //         slug: "shelter",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 62,
    //     title: "Candle Holder",
    //     slug: "candle-holder",
    //     heroImage: require("../assets/characters/shelter/candle-holder.png"),
    //     imagesUrl: [require("../assets/characters/shelter/candle-holder.png")],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Shelter",
    //         slug: "shelter",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 63,
    //     title: "Circus",
    //     slug: "circus",
    //     heroImage: require("../assets/characters/shelter/circus.png"),
    //     imagesUrl: [require("../assets/characters/shelter/circus.png")],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Shelter",
    //         slug: "shelter",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 64,
    //     title: "Fort",
    //     slug: "fort",
    //     heroImage: require("../assets/characters/shelter/fort.png"),
    //     imagesUrl: [require("../assets/characters/shelter/fort.png")],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Shelter",
    //         slug: "shelter",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 65,
    //     title: "Mantel Clock",
    //     slug: "mantel clock",
    //     heroImage: require("../assets/characters/shelter/mantel-clock.png"),
    //     imagesUrl: [require("../assets/characters/shelter/mantel-clock.png")],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Shelter",
    //         slug: "shelter",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 66,
    //     title: "Poet",
    //     slug: "poet",
    //     heroImage: require("../assets/characters/shelter/poet.png"),
    //     imagesUrl: [require("../assets/characters/shelter/poet.png")],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Shelter",
    //         slug: "shelter",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 67,
    //     title: "Sunny Doll",
    //     slug: "sunny doll",
    //     heroImage: require("../assets/characters/shelter/sunny-doll.png"),
    //     imagesUrl: [require("../assets/characters/shelter/sunny-doll.png")],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Shelter",
    //         slug: "shelter",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 68,
    //     title: "Traffic Cone",
    //     slug: "traffic cone",
    //     heroImage: require("../assets/characters/shelter/traffic-cone.png"),
    //     imagesUrl: [require("../assets/characters/shelter/traffic-cone.png")],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Shelter",
    //         slug: "shelter",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 69,
    //     title: "Warrior",
    //     slug: "warrior",
    //     heroImage: require("../assets/characters/shelter/warrior.png"),
    //     imagesUrl: [require("../assets/characters/shelter/warrior.png")],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Shelter",
    //         slug: "shelter",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 70,
    //     title: "Stuffed Bear",
    //     slug: "stuffed bear",
    //     heroImage: require("../assets/characters/shelter/stuffed-bear.png"),
    //     imagesUrl: [require("../assets/characters/shelter/stuffed-bear.png")],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Shelter",
    //         slug: "shelter",
    //     },
    //     maxQuantity: 5,
    // },

    // {
    //     id: 71,
    //     title: "The Businessman",
    //     slug: "the businessman",
    //     heroImage: require("../assets/characters/le-petit-prince/the-businessman.png"),
    //     imagesUrl: [
    //         require("../assets/characters/le-petit-prince/the-businessman.png"),
    //     ],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Le Petit Prince",
    //         slug: "le-petit-prince",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 72,
    //     title: "The Conceited Man",
    //     slug: "the conceited-man",
    //     heroImage: require("../assets/characters/le-petit-prince/the-conceited-man.png"),
    //     imagesUrl: [
    //         require("../assets/characters/le-petit-prince/the-conceited-man.png"),
    //     ],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Le Petit Prince",
    //         slug: "le petit prince",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 73,
    //     title: "The Fox",
    //     slug: "the fox",
    //     heroImage: require("../assets/characters/le-petit-prince/the-fox.png"),
    //     imagesUrl: [
    //         require("../assets/characters/le-petit-prince/the-fox.png"),
    //     ],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Le Petit Prince",
    //         slug: "le petit prince",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 74,
    //     title: "The Geographer",
    //     slug: "the geographer",
    //     heroImage: require("../assets/characters/le-petit-prince/the-geographer.png"),
    //     imagesUrl: [
    //         require("../assets/characters/le-petit-prince/the-geographer.png"),
    //     ],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Le Petit Prince",
    //         slug: "le petit prince",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 75,
    //     title: "The King",
    //     slug: "the king",
    //     heroImage: require("../assets/characters/le-petit-prince/the-king.png"),
    //     imagesUrl: [
    //         require("../assets/characters/le-petit-prince/the-king.png"),
    //     ],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Le Petit Prince",
    //         slug: "le petit prince",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 76,
    //     title: "The Lamplighter",
    //     slug: "the lamplighter",
    //     heroImage: require("../assets/characters/le-petit-prince/the-lamplighter.png"),
    //     imagesUrl: [
    //         require("../assets/characters/le-petit-prince/the-lamplighter.png"),
    //     ],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Le Petit Prince",
    //         slug: "le petit prince",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 77,
    //     title: "The Little Prince",
    //     slug: "the little prince",
    //     heroImage: require("../assets/characters/le-petit-prince/the-little-prince.png"),
    //     imagesUrl: [
    //         require("../assets/characters/le-petit-prince/the-little-prince.png"),
    //     ],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Le Petit Prince",
    //         slug: "le petit prince",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 78,
    //     title: "The Merchant",
    //     slug: "the merchant",
    //     heroImage: require("../assets/characters/le-petit-prince/the-merchant.png"),
    //     imagesUrl: [
    //         require("../assets/characters/le-petit-prince/the-merchant.png"),
    //     ],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Le Petit Prince",
    //         slug: "le petit prince",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 79,
    //     title: "The Pilot",
    //     slug: "the pilot",
    //     heroImage: require("../assets/characters/le-petit-prince/the-pilot.png"),
    //     imagesUrl: [
    //         require("../assets/characters/le-petit-prince/the-pilot.png"),
    //     ],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Le Petit Prince",
    //         slug: "le petit prince",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 80,
    //     title: "The Rose",
    //     slug: "the rose",
    //     heroImage: require("../assets/characters/le-petit-prince/the-rose.png"),
    //     imagesUrl: [
    //         require("../assets/characters/le-petit-prince/the-rose.png"),
    //     ],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Le Petit Prince",
    //         slug: "le petit prince",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 81,
    //     title: "The Snake",
    //     slug: "the snake",
    //     heroImage: require("../assets/characters/le-petit-prince/the-snake.png"),
    //     imagesUrl: [
    //         require("../assets/characters/le-petit-prince/the-snake.png"),
    //     ],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Le Petit Prince",
    //         slug: "le petit prince",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 82,
    //     title: "The Switchman",
    //     slug: "the switchman",
    //     heroImage: require("../assets/characters/le-petit-prince/the-switchman.png"),
    //     imagesUrl: [
    //         require("../assets/characters/le-petit-prince/the-switchman.png"),
    //     ],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Le Petit Prince",
    //         slug: "le petit prince",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 83,
    //     title: "The Tippler",
    //     slug: "the tippler",
    //     heroImage: require("../assets/characters/le-petit-prince/the-tippler.png"),
    //     imagesUrl: [
    //         require("../assets/characters/le-petit-prince/the-tippler.png"),
    //     ],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Le Petit Prince",
    //         slug: "le petit prince",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 84,
    //     title: "Special Prince",
    //     slug: "special",
    //     heroImage: require("../assets/characters/le-petit-prince/special.png"),
    //     imagesUrl: [
    //         require("../assets/characters/le-petit-prince/special.png"),
    //     ],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Le Petit Prince",
    //         slug: "le petit prince",
    //     },
    //     maxQuantity: 5,
    // },

    // {
    //     id: 102,
    //     title: "Hiirono1",
    //     slug: "hirono1",
    //     heroImage: require("../assets/characters/hirono trial.png"),
    //     imagesUrl: [require("../assets/characters/hirono trial.png")],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Pops",
    //         slug: "pops",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 103,
    //     title: "Hiirono2",
    //     slug: "hirono2",
    //     heroImage: require("../assets/characters/hirono trial.png"),
    //     imagesUrl: [require("../assets/characters/hirono trial.png")],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Pops",
    //         slug: "pops",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 104,
    //     title: "Hiirono3",
    //     slug: "hirono3",
    //     heroImage: require("../assets/characters/hirono trial.png"),
    //     imagesUrl: [require("../assets/characters/hirono trial.png")],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Pops",
    //         slug: "pops",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 105,
    //     title: "Hiirono4",
    //     slug: "hirono4",
    //     heroImage: require("../assets/characters/hirono trial.png"),
    //     imagesUrl: [require("../assets/characters/hirono trial.png")],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Pops",
    //         slug: "pops",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 106,
    //     title: "png img",
    //     slug: "adventure-time",
    //     heroImage: require("../assets/characters/adventure-time.png"),
    //     imagesUrl: [require("../assets/characters/adventure-time.png")],
    //     price: 899.99,
    //     category: {
    //         imageUrl: require("../assets/characters/box_img.webp"),
    //         name: "Pops",
    //         slug: "pops",
    //     },
    //     maxQuantity: 5,
    // },
    // {
    //     id: 100,
    //     title: "IPhone 15",
    //     slug: "i-phone-15",
    //     heroImage: require("../assets/images/i-phone-1.jpg"),
    //     imagesUrl: [
    //         require("../assets/images/i-phone-2.jpg"),
    //         require("../assets/images/i-phone-3.jpg"),
    //     ],
    //     price: 999.99,
    //     category: {
    //         imageUrl: require("../assets/images/i-phone-1.jpg"),
    //         name: "Phones",
    //         slug: "phones",
    //     },
    //     maxQuantity: 10,
    // },
    // {
    //     id: 101,
    //     title: "Samsung Galaxy S21",
    //     slug: "samsung-galaxy-s21",
    //     heroImage: require("../assets/images/samsung-1.jpg"),
    //     imagesUrl: [
    //         require("../assets/images/samsung-1.jpg"),
    //         require("../assets/images/samsung-2.jpg"),
    //     ],
    //     price: 799.99,
    //     category: {
    //         imageUrl: require("../assets/images/i-phone-1.jpg"),
    //         name: "Phones",
    //         slug: "phones",
    //     },
    //     maxQuantity: 12,
    // },
];
